2020-10-28 20:17:04.071682
Traceback (most recent call last):
  File "/home/obojetnie/python/Program/klasy111.py", line 20, in BazaDanych
    database="covid")
  File "/home/obojetnie/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "covid" does not exist



2020-10-28 20:18:36.362508
Traceback (most recent call last):
  File "/home/obojetnie/python/Program/klasy111.py", line 20, in BazaDanych
    database="covid")
  File "/home/obojetnie/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "covid" does not exist



